#@ load("@ytt:data", "data")
---
apiVersion: scanning.apps.tanzu.vmware.com/v1beta1
kind: ScanPolicy
metadata:
  name: scan-policy
  namespace: #@ data.values.tap.devNamespace
  labels:
    'app.kubernetes.io/part-of': 'component-a'
spec:
  regoFile: |
    package main

    notAllowedSeverities := ["Critical", "High", "UnknownSeverity", "Negligible"]
    ignoreCves := ["CVE-2016-1000027", "GHSA-6v73-fgf6-w5j7", "GHSA-36p3-wjmg-h94x", "CVE-2015-0244", "CVE-2015-3166", "CVE-2018-1115", "CVE-2019-10211", "CVE-2015-0241", "CVE-2015-0242", "CVE-2015-0243", "CVE-2015-3167", "CVE-2016-0766", "CVE-2016-0768", "CVE-2016-0773", "CVE-2016-5423", "CVE-2016-5424", "CVE-2016-7048", "CVE-2017-14798", "CVE-2017-7484", "CVE-2019-10127", "CVE-2019-10128", "CVE-2019-10210", "CVE-2020-25694", "CVE-2020-25695", "CVE-2021-23214", "GHSA-88cc-g835-76rp", "GHSA-r38f-c4h4-hqq2", "CVE-2021-26291", "GHSA-36p3-wjmg-h94x""CVE-2016-0948", "CVE-2016-0949", "CVE-2016-4118", "CVE-2017-11291", "CVE-2017-3101", "CVE-2018-12804", "CVE-2018-12805", "CVE-2018-4923", "CVE-2018-4994", "CVE-2020-5674", "CVE-2021-21085", "CVE-2021-40719", "CVE-2017-18589", "CVE-2018-25076",  "GHSA-rc47-6667-2j5j", "GHSA-9c47-m6qq-7p4h", "CVE-2014-9488", "CVE-2022-37599", "CVE-2022-37603", "GHSA-3rfm-jhwj-7488", "GHSA-hhq3-ff78-jv3g", "GHSA-fhg7-m89q-25r3"]

    contains(array, elem) = true {
      array[_] = elem
    } else = false { true }

    isSafe(match) {
      severities := { e | e := match.ratings.rating.severity } | { e | e := match.ratings.rating[_].severity }
      some i
      fails := contains(notAllowedSeverities, severities[i])
      not fails
    }

    isSafe(match) {
      ignore := contains(ignoreCves, match.id)
      ignore
    }

    deny[msg] {
      comps := { e | e := input.bom.components.component } | { e | e := input.bom.components.component[_] }
      some i
      comp := comps[i]
      vulns := { e | e := comp.vulnerabilities.vulnerability } | { e | e := comp.vulnerabilities.vulnerability[_] }
      some j
      vuln := vulns[j]
      ratings := { e | e := vuln.ratings.rating.severity } | { e | e := vuln.ratings.rating[_].severity }
      not isSafe(vuln)
      msg = sprintf("CVE %s %s %s", [comp.name, vuln.id, ratings])
    }
