namespace: tap-dev
targetImagePullSecret: "registry-credentials"
carbonBlack:
  configSecret:
    name: carbonblack-token-secret
metadataStore:
  caSecret:
    importFromNamespace: ""
  authSecret:
    importFromNamespace: ""