
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "kkadourah@vmware.com"
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
    - dns01:
        cloudflare:
          email: "kadourah@gmail.com"
          apiKeySecretRef:
            name: cloudflare-api-key-secret
            key: api-key
