#@ load("@ytt:data", "data")
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-http01-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: yunusa.namadi@gmail.com
    privateKeySecretRef:
      name: letsencrypt-http01-issuer
    solvers:
      - http01:
          ingress:
            class: contour
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls
  namespace: tanzu-system-ingress
spec:
  commonName: '*.tanzu.y-compiles.com'
  secretName: tls
  issuerRef:
    name: letsencrypt-http01-issuer
    kind: ClusterIssuer
  dnsNames:
  - '*.tanzu.y-compiles.com'
  - harbor.y-compiles.com