#@ load("@ytt:data", "data")
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kadourah.com
  namespace: tanzu-system-ingress
spec:
  secretName: tls
  privateKey:
      rotationPolicy: Always
  dnsNames:
    - '*.apps.tap.tanzu.kadourah.com'
    - 'tap-gui.tap.tanzu.kadourah.com'
    - 'metadata-store.tap.tanzu.kadourah.com'
    - 'learning-center-guided.learningcenter.tap.tanzu.kadourah.com'
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer

---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: tls
  namespace: tanzu-system-ingress
spec:
  toNamespace: learningcenter
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: tls
  namespace: learningcenter
spec:
  fromNamespace: tanzu-system-ingress