#@ load("@ytt:data", "data")
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: y-compiles.com
  namespace: tanzu-system-ingress
spec:
  commonName: tap-gui.tap.tanzu.y-compiles.com
  isCA: true
  secretName: tls
  privateKey:
      rotationPolicy: Always
  dnsNames:
    - '*.apps.tap.tanzu.y-compiles.com'
    - 'tap-gui.tap.tanzu.y-compiles.com'
    - 'metadata-store.tap.tanzu.y-compiles.com'
    - '*.learningcenter.tap.tanzu.y-compiles.com'
  issuerRef:
    group: cert-manager.io
    name: letsencrypt-production
    kind: ClusterIssuer

---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: tls
  namespace: tanzu-system-ingress
spec:
  toNamespace: learningcenter
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: tls
  namespace: learningcenter
spec:
  fromNamespace: tanzu-system-ingress