#@ load("@ytt:data", "data")
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  annotations:
    kapp.k14s.io/change-rule.0: "delete after deleting tanzu-app-platform"
type: Opaque
stringData:
  api-token: #@ data.values.tap.credentials.cloudflare.api-token