#@ load("@ytt:data", "data")
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  annotations:
    kapp.k14s.io/change-group: "letsencrypt-cert-issuer"
    kapp.k14s.io/change-rule.cert-manager: "upsert after upserting cert-manager"
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: kadourah@gmail.com
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
    - dns01:
        cloudflare:
          email: kadourah@gmail.com
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token