#@ load("@ytt:data", "data")
---
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kadourah.com
  namespace: tanzu-system-ingress
  annotations:
    kapp.k14s.io/change-group: "tls-cert-request"
    kapp.k14s.io/change-rule.cert-manager: "upsert after upserting cert-manager"
    kapp.k14s.io/change-rule.tanzu-app-platform: "upsert after upserting tanzu-app-platform"
    kapp.k14s.io/change-rule.tanzu-app-platform-configs: "upsert after upserting tanzu-app-platform-configs"
    kapp.k14s.io/change-rule.3: "delete after deleting tanzu-app-platform"
spec:
  secretName: tls
  privateKey:
      rotationPolicy: Always
  dnsNames:
    - '*.apps.tap.tanzu.kadourah.com'
    - 'tap-gui.tap.tanzu.kadourah.com'
    - 'metadata-store.tap.tanzu.kadourah.com'
    - 'learning-center-guided.learningcenter.tap.tanzu.kadourah.com'
  issuerRef:
    name: cloudflare-issuer
    kind: ClusterIssuer
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: tls
  namespace: tanzu-system-ingress
  annotations:
    kapp.k14s.io/change-rule.0: "upsert after upserting tanzu-app-platform"
    kapp.k14s.io/change-rule.1: "upsert after upserting tanzu-app-platform-configs"
    kapp.k14s.io/change-rule.2: "delete after deleting tanzu-app-platform"
spec:
  toNamespaces:
  - '*'
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: tls
  namespace: learningcenter
  annotations:
    kapp.k14s.io/change-group: "import-tls-secret-to-learningcenter"
    kapp.k14s.io/change-rule.0: "upsert after upserting tanzu-app-platform"
    kapp.k14s.io/change-rule.1: "upsert after upserting tanzu-app-platform-configs"
    kapp.k14s.io/change-rule.2: "delete after deleting tanzu-app-platform"
spec:
  fromNamespace: tanzu-system-ingress